CREATE TABLE teams (
    ID INTEGER PRIMARY KEY,
    Abbreviation VARCHAR(4) NOT NULL
);

CREATE TABLE countries (
    ID INTEGER PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE colleges (
    ID INTEGER PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE players (
    ID INTEGER PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Age INTEGER NOT NULL,
    Height FLOAT NOT NULL,
    Weight FLOAT NOT NULL,
    DraftYear INT NOT NULL,
    DraftRound INT NOT NULL,
    DraftNumber INT NOT NULL,
    CollegeRef INTEGER REFERENCES Colleges(ID),
    CountryRef INTEGER REFERENCES Countries(ID) NOT NULL
);

CREATE TABLE entries (
    ID INTEGER PRIMARY KEY,
    Season VARCHAR(8) NOT NULL,
    GP INTEGER NOT NULL,
    PTS FLOAT NOT NULL,
    REB FLOAT NOT NULL,
    AST FLOAT NOT NULL,
    NetRating FLOAT NOT NULL,
    OREBPct FLOAT NOT NULL,
    DREBPct FLOAT NOT NULL,
    USGPct FLOAT NOT NULL,
    TSPct FLOAT NOT NULL,
    ASTPct FLOAT NOT NULL,
    PlayerRef INTEGER REFERENCES Players(ID) NOT NULL,
    TeamRef INTEGER REFERENCES Teams(ID) NOT NULL
);